export const CONTACT_SUBMIT_START = 'CONTACT_SUBMIT_START';
export const CONTACT_SUBMIT_SUCCESS = 'CONTACT_SUBMIT_SUCCESS';
export const CONTACT_SUBMIT_FAIL = 'CONTACT_SUBMIT_FAIL';
export const CONTACT_RESET = 'CONTACT_RESET';
